### ISSUE TITLE
Error al buscar

### ISSUE THREAD

**Issue by ljimenezg** [Cuevana/storm#126]
Al digitar más de 3 letras lanza un error 
Uncaught node.js Error 
TypeError: Cannot read property 'length' of undefined
    at t.renderGrid (app://cuevana/js/main.js:533:83)
    at callback (app://cuevana/js/main.js:486:7)
    at Request.eval [as _callback](app://cuevana/js/main.js:508:6)
.....

**Comment by kike13** [comment]
Tengo el mismo error

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.

**Comment by kike13** [comment]
Así es, ahora funciona perfectamente. Gracias a vosotros
