### ISSUE TITLE
Cuevana Storm player doesn't work in my mac

### ISSUE THREAD

**Issue by brebolledo** [Cuevana/storm#137]
Hello, I just updated cuevana storm to the new version you release but I have the same issue as before. Since I updated to Mavericks, the player doesn't work. It says its downloading the torrent, but it just stuck in 00:00 and the play button is not working. What could I do?

**Comment by Cuevana** [comment]
User @olivercs seems to have found the issue. We already updated the repo with the fix. Expect a compiled app in the next few days.

**Comment by bjornpost** [comment]
Just compiled the Cuevana from src and @olivercs's change does not fix the issue I'm seeing. I can't get a video to start playing.

The issue seems to be in `PlayerCtrl.js`, where the `watchPlayer` watch function can't find the video element:

```
[98189:0920/090617:INFO:CONSOLE(10671)] ""TypeError: Cannot read property 'scope' of null
    at Object.\u003Canonymous\u003E (app://cuevana/app/js/controllers/PlayerCtrl.js:57:86)
    at Scope.$digest (app://cuevana/bower_components/angular/angular.js:13254:40)
    at Scope.$apply (app://cuevana/bower_components/angular/angular.js:13528:24)
    at app://cuevana/bower_components/angular/angular.js:15255:36
    at completeOutstandingRequest (app://cuevana/bower_components/angular/angular.js:4554:10)
    at app://cuevana/bower_components/angular/angular.js:4861:7"", source: app://cuevana/bower_components/angular/angular.js (10671)
```

When pressing play manually:

```
[98272:0920/091854:INFO:CONSOLE(10671)] ""TypeError: undefined is not a function
    at Scope.h.play (app://cuevana/bower_components/angular-media-player/dist/angular-media-player.min.js:1:1489)
    at Scope.h.playPause (app://cuevana/bower_components/angular-media-player/dist/angular-media-player.min.js:1:1671)
    at Scope.scope.togglePause (app://cuevana/app/js/directives/stPlayerControls.js:133:18)
    at $parseFunctionCall (app://cuevana/bower_components/angular/angular.js:11445:18)
    at callback (app://cuevana/bower_components/angular/angular.js:21629:17)
    at Scope.$eval (app://cuevana/bower_components/angular/angular.js:13424:28)
    at Scope.$apply (app://cuevana/bower_components/angular/angular.js:13522:23)
    at HTMLAnchorElement.\u003Canonymous\u003E (app://cuevana/bower_components/angular/angular.js:21634:23)
    at HTMLAnchorElement.jQuery.event.dispatch (app://cuevana/bower_components/jquery/dist/jquery.js:4409:9)
    at HTMLAnchorElement.elemData.handle (app://cuevana/bower_components/jquery/dist/jquery.js:4095:28)"", source: app://cuevana/bower_components/angular/angular.js (10671)
```

But I guess that's related to the video element which can't be found. I can confirm (using the web inspector) that a video element is available in the DOM.

---

Just found out there is a fork of `angular-media-player` in your repo which is not loaded using `bower.json` (instead it just uses the repo by mrgamer). Maybe that's the issue?

**Comment by olivercs** [comment]
The fixed didnt work if you compile from scratch. Just editing the compiles
version. When i tried to compile from scratch i notice that the vídeo tag
was not working.

**Comment by olivercs** [comment]
If you try to open the video url in browser, you can see the video.

**Comment by Cuevana** [comment]
We got to try out @olivercs solution but always get address `0.0.0.0` which breaks anywhere that interface address doesn't point to local IP. So it's not actually solving the issue. We are reverting for now.

We need to get data from environments where this issue is happening. Not our case unfortunately, so it's difficult to test. If someone with this particular problem would like to assist us in finding the issue, please let us know.

**Comment by olgabart** [comment]
krill96 mil gracias, funciona perfectamente!

**Comment by serrot3** [comment]
help cuevana app doesn't work it just won't load the videos whats wrong, I've tried to uninstall it but this won't solve the problem it just appears a dark screen

**Comment by brebolledo** [comment]
the same happens to me since this morning. weird Its loading but nothing
appears.

On 2 February 2015 at 22:02, serrot3 notifications@github.com wrote:

> help cuevana app doesn't work it just won't load the videos whats wrong,
> I've tried to uninstall it but this won't solve the problem it just appears
> a dark screen
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cuevana/storm/issues/137#issuecomment-72597466.

## 

Bárbara Paz Rebolledo Bustamante

@barbarapazr
www.barbararebolledo.com
_http://brebolledo.tumblr.com/ http://brebolledo.tumblr.com/_
www.flickr.com/photos/copa_d

**Comment by alainrochette** [comment]
@serrot3 @brebolledo @Cuevana same thing since today: nothing loads, just a dark screen. uninstalled, restarted computer, tried everything. please fix!

**Comment by alainrochette** [comment]
still waiting for a reply...

**Comment by so97** [comment]
same here! it opens and loads and nothing appears only black screen

**Comment by casosa26** [comment]
Within the past couple of days I've noticed that Cuevana Storm won't load its videos at all. I attempted to delete the application and download it again but it won't work. The app would show me a black screen. Please help me fixing this issue!

**Comment by provehito** [comment]
I have the same problem as 'casosa26 ', the app for Mac doesn't load videos and I only see a black screen, the menu scroll works though, but I would like to know if there is a fix coming soon.

I have OSX Yosemite, I don't know if there is a incompatibility in the way it streams the video into the menu or something.

**Comment by Sh4rky** [comment]
Same problem, since last week it doesn't  load anything

**Comment by mfsoley** [comment]
same problem!! someone help please!

**Comment by anguivego** [comment]
same happen to me.

**Comment by For2** [comment]
I have the same problem. Did try to download 2 or 3 times. but it persist. would it be any changed or the problem will remain at it is!!!!?????? 
:/

**Comment by provehito** [comment]
I try to open it in my other pc that I have and has Windows 8.1 Pro and same thing. I believe that this is not an OS problem, this is a provider problem, meaning Cuevana. They are the ones with the problem and we will have to sit and wait while they fix it.

Cr**p!

**Comment by For2** [comment]
Mmmm… I guess so. Kind of disappointed. But well…

**Comment by alainrochette** [comment]
it would be greaaat if cuevana could reply right naw

**Comment by Cuevana** [comment]
The issue comes from Cuevana's API, that is currently offline. We are trying to reactivate the service. If you care to help us a donation is welcome to support our servers. We hope to be back online in short time. More info at: https://www.facebook.com/cuevanaoficial

**Comment by brebolledo** [comment]
I can't access the link to donate :(

On 11 February 2015 at 19:24, Cuevana notifications@github.com wrote:

> The issue comes from Cuevana's API, that is currently offline. We are
> trying to reactivate the service. If you care to help us a donation is
> welcome to support our servers. We hope to be back online in short time.
> More info at: https://www.facebook.com/cuevanaoficial
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cuevana/storm/issues/137#issuecomment-74011462.

## 

Bárbara Paz Rebolledo Bustamante

@barbarapazr
www.barbararebolledo.com
_http://brebolledo.tumblr.com/ http://brebolledo.tumblr.com/_
www.flickr.com/photos/copa_d

**Comment by alainrochette** [comment]
same problem again for the past few months: black screen on mac. cuevana whattheheck...gone are the days when you were reliable and sturdy
