### ISSUE TITLE
Playback problems

### ISSUE THREAD

**Issue by Ulovlig** [Cuevana/storm#152]
Hi, I also have the issue where player not starting the playback. 
Only says 00:00 / 00:00. Torrent is downloading though. 
I did open console to see if any error messages where displayed and got this: 

TypeError: Cannot read property 'getAttribute' of null
    at Object.<anonymous> (app://cuevana/app/js/directives/stVolumeSlider.js:32:22)
    at Scope.$digest (app://cuevana/bower_components/angular/angular.js:13266:40)
    at Scope.$apply (app://cuevana/bower_components/angular/angular.js:13540:24)
    at app://cuevana/app/js/controllers/PlayerCtrl.js:85:11
    at Scope.$emit (app://cuevana/bower_components/angular/angular.js:13678:33)
    at app://cuevana/app/js/services/Player.js:110:16
    at loadingStats (app://cuevana/app/js/node/playtorrent.js:88:6) angular.js:10683

I've tried both downloading from cuevana.tv and build from source here. Using Windows 7. Also
tried the npm run/start command.

**Comment by guzmanuy** [comment]
Hi, i have the same problem, and i am using Windows 8.1.
