### ISSUE TITLE
Buscador

### ISSUE THREAD

**Issue by juanmacio** [Cuevana/storm#96]
El buscador no funciona.

Tampoco el selector de generos de las peliculas.

Sucede también que cuando buscas peliculas/series por categoria (Estrenos, Populares del mes, Ranking...) y cliqueas en una para ver de que se trata y luego cerrás, no sigue cargando la lista de peliculas/series en esa categoria.

**Comment by juanmacio** [comment]
El buscador funciona ahora!

El resto sigue igual.

**Comment by cdagnino** [comment]
Bajé la aplicación hoy y el buscador funciona sólo a veces. Este es el traceback que me entrega:

``` javascript
Uncaught node.js Error 

TypeError: Cannot read property 'length' of undefined
    at t.renderGrid (app://cuevana/js/main.js:525:83)
    at callback (app://cuevana/js/main.js:478:7)
    at Request.eval [as _callback] (app://cuevana/js/main.js:500:6)
    at Request.self.callback (/Applications/Cuevana Storm.app/Contents/Resources/app.nw/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:101:17)
    at Request.eval (/Applications/Cuevana Storm.app/Contents/Resources/app.nw/node_modules/request/request.js:978:14)
    at Request.EventEmitter.emit (events.js:120:20)
    at IncomingMessage.eval (/Applications/Cuevana Storm.app/Contents/Resources/app.nw/node_modules/request/request.js:929:12)
    at IncomingMessage.EventEmitter.emit (events.js:120:20)
    at eval (_stream_readable.js:896:16)
```

**Comment by Cuevana** [comment]
Lanzamos una nueva versión de la app, debería solucionar este problema. Gracias.

**Comment by carlos63p** [comment]
Buenas tardes en el cueva storm no me esta funcionando el buscador de peliculas :/ que podra ser?
Tampoco el selector de generos de las peliculas.

**Comment by juanmacio** [comment]
@carlos63p estás usando la última versión? Podés descargarla de www.cuevana.tv

**Comment by carlos63p** [comment]
si estoy usando la nueva versiónn juanmacio gracias por tu respuesta :D

**Comment by ghost** [comment]
Buenas tardes, como puedo descargar la nueva version ? El link de Mega esta caído. Saludos !!!
